name: DEPLOY_TO_DEV

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1

      - name: Listing all files
        run: ls -ltr

      # Copy file to s3
      - name: Copy cloudformation template to s3
        run: |
          aws s3 cp ./data-engineering-infra/cloudformation/data-engineering/.
          s3://data-engineering-shared/data-engineering-stack  --recursive
